# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8981ba4699faf22ddcaebc03c292817d78e93106c9631af6334f337ee7b71a653237697a2a7d8918557820674fbebbf0c1be343dabc432ec98901607eb750d8

test:
  secret_key_base: cd2d5ce1bdbb42f48307db77d5f1a305cacb48931ae43304d0a97030548e1f58f5071e6d00d575e72a8b192076a6e8b423d0a1fabb88e6d5b7351272c69e1b2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
